-- Add Alpha Vantage financial ratio columns to fundamentals table
ALTER TABLE fundamentals
ADD COLUMN IF NOT EXISTS beta DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS forward_pe DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS peg_ratio DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS profit_margin DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS earnings_growth DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS revenue_growth DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS analyst_target DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS book_value DOUBLE PRECISION;
